# Generated by Django 2.2.2 on 2019-08-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='queries',
            new_name='quaries',
        ),
    ]
