# Generated by Django 2.2.2 on 2019-08-28 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0002_auto_20190828_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quaries',
            name='created_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
