# Generated by Django 2.2.2 on 2019-08-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0003_auto_20190828_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('collegename', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=200)),
                ('pic', models.ImageField(upload_to='facultypic')),
                ('contact', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('pic', models.ImageField(upload_to='studentpic')),
                ('achievement', models.TextField()),
                ('rank', models.FloatField()),
                ('program', models.CharField(max_length=300)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
