# Generated by Django 2.2.2 on 2019-08-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0004_faculties_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='centers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('place', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=300)),
                ('years', models.PositiveIntegerField()),
                ('fees', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=300)),
            ],
        ),
    ]
