# Generated by Django 2.2.2 on 2019-08-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0006_auto_20190828_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='rankers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('pic', models.ImageField(upload_to='studentpic')),
                ('achievement', models.TextField()),
                ('rank', models.FloatField()),
                ('program', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('pic', models.ImageField(upload_to='studentpic')),
                ('fathername', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('program', models.CharField(max_length=300)),
                ('joinyear', models.PositiveIntegerField()),
                ('pyear', models.PositiveIntegerField()),
                ('feestatus', models.CharField(default='Not paid', max_length=50)),
                ('fee', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
