# Generated by Django 2.2.2 on 2019-08-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0007_auto_20190828_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='pic',
            field=models.ImageField(upload_to='media/facultypic'),
        ),
    ]
