# Generated by Django 2.2.2 on 2019-08-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0008_auto_20190831_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='pic',
            field=models.ImageField(upload_to='facultypic/'),
        ),
        migrations.AlterField(
            model_name='rankers',
            name='pic',
            field=models.ImageField(upload_to='studentpic/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='pic',
            field=models.ImageField(upload_to='studentpic/'),
        ),
    ]
