# Generated by Django 2.2.2 on 2019-08-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0009_auto_20190831_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculties',
            name='pic',
        ),
    ]
