# Generated by Django 2.2.2 on 2019-08-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0010_remove_faculties_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculties',
            name='pic',
            field=models.ImageField(default='img/user.png', upload_to='facultypic/'),
        ),
    ]
