# Generated by Django 2.2.2 on 2019-08-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0012_auto_20190831_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculties',
            name='address',
            field=models.TextField(default='NOT_PROVIDED'),
        ),
        migrations.AddField(
            model_name='faculties',
            name='email',
            field=models.EmailField(default='NOT_PROVIDED', max_length=254),
        ),
    ]
