# Generated by Django 2.2.2 on 2019-08-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0013_auto_20190831_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='email',
            field=models.EmailField(default='not@provided.com', max_length=254),
        ),
    ]
