# Generated by Django 2.2.2 on 2019-08-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0015_auto_20190831_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankers',
            name='rank',
            field=models.CharField(max_length=100),
        ),
    ]
