# Generated by Django 2.2.2 on 2019-08-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0016_auto_20190831_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='center',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
