# Generated by Django 2.2.2 on 2019-09-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperate', '0017_students_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculties',
            name='center',
            field=models.CharField(default='Jamshedpur', max_length=250),
        ),
    ]
